language: c

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

script:
  - ./autogen.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt update && sudo apt install python3-dev libiberty-dev libzstd-dev clang; ./configure; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --without-libiberty; fi
  - make
  - make check

matrix:
  include:
  - os: linux
    compiler: gcc
    dist: xenial
  - os: linux
    compiler: clang
    dist: xenial
  - os: osx
    osx_image: xcode8.2
    env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  - os: osx
    osx_image: xcode8.2
    compiler: clang
  - os: osx
    osx_image: xcode8.3
    compiler: clang
  - os: osx
    osx_image: xcode9
    compiler: clang
